name = "hosts"
main = "src/index.ts"
compatibility_date = "2024-10-28"
compatibility_flags = ["nodejs_compat"]
assets = { directory = "public" }

# [vars]
# API_KEY = ""

[[kv_namespaces]]
binding = "hosts"
id = "2e8ad57a3acc4cb5943b474ec507b715"


# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

[observability]
enabled = true
head_sampling_rate = 1

[triggers]
crons = ["0 */1 * * *"]
